homeDirectories:
  nfs:
    serverIP: 10.240.0.7
    serverName: homes/prod

jupyterhub:
  proxy:
    #service:
    #  loadBalancerIP: 35.232.190.188
    https:
      hosts:
        - data100.datahub.berkeley.edu
      letsencrypt:
        contactEmail: rylo@berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 40Gi
