nfsMounter:
  mounts:
    - 10.240.0.7:/homes/prod/home=/homes/prod

homeDirectories:
  nfs:
    serverIP: 10.240.0.7
    serverName: homes/prod

jupyterhub:
  proxy:
    #service:
    #  loadBalancerIP: 35.232.190.188
    https:
      hosts:
        - data100.datahub.berkeley.edu
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /homes/prod/{username}
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
